name: dev
on:
  workflow_dispatch:
  push:
    paths:
      - bin/**
      - glrd/**
      - tests/**
      - poetry.lock
      - pyproject.toml
jobs:
  test:
    name: test
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install GLRD and dependencies
        run: poetry install --with dev
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
